### ISSUE TITLE
Inclure le script et l'installation pour gitinspector?

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-jeu-de-des-node-express-ts#97]
Dans les notes de cours on a une explication de comment utiliser le script dans le gist à https://gist.github.com/fuhrmanator/b5b098470e7ec4536c35ca1ce3592853

J'ai l'impression que c'est finalement peu utilisé par les étudiants.

Devrions-nous plutôt inclure ce script dans le squelette? Si oui, il faudrait:

- ajouter une installation de gitinspector dans package.json
- ~~installer python (ça complique les choses un peu, mais p-e avec un environnement virtuel ça peut bien aller dans un projet node.js)~~ [le support python est normalement installé par npm]

**Comment by yvanross** [comment]
C'est fait. J'ai aussi inclus l'information dans l'énoncé.

**Comment by fuhrmanator** [comment]
As-tu testé? J'ai vu que ça ne marche plus sur Windows à cause d'un changement dans python 3. https://github.com/ejwa/gitinspector/issues/213

**Comment by imBigo** [comment]
> As-tu testé? J'ai vu que ça ne marche plus sur Windows à cause d'un changement dans python 3. [ejwa/gitinspector#213](https://github.com/ejwa/gitinspector/issues/213)

Je confirme que c'est encore un problème sur Windows 10:
```
Traceback (most recent call last):
  File "C:\Users\simon\AppData\Roaming\npm\node_modules\gitinspector\gitinspector.py", line 21, in <module>
    from gitinspector import gitinspector
  File "C:\Users\simon\AppData\Roaming\npm\node_modules\gitinspector\gitinspector\gitinspector.py", line 26, in <module>
    from .blame import Blame
  File "C:\Users\simon\AppData\Roaming\npm\node_modules\gitinspector\gitinspector\blame.py", line 28, in <module>
    from .changes import FileDiff
  File "C:\Users\simon\AppData\Roaming\npm\node_modules\gitinspector\gitinspector\changes.py", line 29, in <module>
    from . import extensions, filtering, format, interval, terminal
  File "C:\Users\simon\AppData\Roaming\npm\node_modules\gitinspector\gitinspector\format.py", line 28, in <module>
    from . import basedir, localization, terminal, version
  File "C:\Users\simon\AppData\Roaming\npm\node_modules\gitinspector\gitinspector\version.py", line 23, in <module>
    localization.init()
  File "C:\Users\simon\AppData\Roaming\npm\node_modules\gitinspector\gitinspector\localization.py", line 71, in init
    __translation__.install(True)
  File "C:\Users\simon\miniconda3\lib\gettext.py", line 354, in install
    for name in allowed & set(names):
TypeError: 'bool' object is not iterable
```

**Comment by fuhrmanator** [comment]
Une solution pour la configuration problématique de Python serait d'utiliser la fork à https://github.com/jpwhite3/gitinspector qui a abandonné le code pour Python 2. Par contre, il n'y a pas un package NPM pour celui-là. 

Sinon, quelqu'un a proposé un Dockerfile: https://github.com/ejwa/gitinspector/pull/219/commits/c891985de3f2a819d8cf84c498251f03650df39c et c'est pour Python 3.7 (si l'image est encore disponible?) avant que les pb de gettext.py existent.

Ces deux solutions nécessitent une adaptation du script dans le gist à https://gist.github.com/fuhrmanator/b5b098470e7ec4536c35ca1ce3592853, car il fonctionne avec une command NPM.

**Comment by fuhrmanator** [comment]
J'ai réussi à rouler un docker construit avec https://github.com/ejwa/gitinspector/commit/c891985de3f2a819d8cf84c498251f03650df39c, mais c'est compliqué (au moins sur Windows et git bash). Voici l'explication de la commande par ChatGPT: https://chat.openai.com/share/34e5b946-3189-4bcd-91de-c17e49d54391

```bash
MSYS_NO_PATHCONV=1 docker run --rm -it -v "$(cygpath -w "$(pwd)"):/repo" gitinspector -f ts,puml,plantuml,md -m -r -T -w /repo -F html > myresults.html
```

La ligne va analyser le dépôt dans le répertoire courant. Il serait possible de modifier le script

**Comment by fuhrmanator** [comment]
J'ai modifié le script sh pour que ça fonctionne avec un docker. Sans ChatGPT, je pense que cela m'aurait pris un temps fou!  

```sh
#!/bin/bash
authorsToExcludeArray=("Christopher Fuhrman" "Yvan Ross")
reportPrefix="ContributionsÉquipe"
reportTests="${reportPrefix}Test.html"
reportModels="${reportPrefix}Modèles.html"
reportTypeScript="${reportPrefix}TypeScript.html"
reportViews="${reportPrefix}Views.html"
reportDocumentation="${reportPrefix}Docs.html"
nArgs=$#
args=("$@")
gitinspector_image="gitinspector"
# expand in case a "." or relative directory is passed.
repo_dir=$(realpath "$1")
repo_name=$(basename "$repo_dir")
docker_command="MSYS_NO_PATHCONV=1 docker run --rm -it -v $repo_dir:/$repo_name $gitinspector_image"
globalOptions="--localize-output -w /$repo_name --grading --format=html"

function docker_image_exists() {
  local image_name="$1"
  
  if docker image inspect "$image_name" >/dev/null 2>&1; then
    echo "Docker image $image_name exists locally."
    return 0
  else
    echo "Error: Docker image $image_name does not exist locally."
    return 1
  fi
}

# modified from https://gist.github.com/JamieMason/4761049
function npm_package_is_installed {
  # set to 1 initially
  local return_=1
  # set to 0 if not found
  npm list -g 2>/dev/null | grep $1 >/dev/null 2>&1 || { local return_=0; }
  # return value
  echo "$return_"
}

function authors_to_exclude() {
  local array_="${authorsToExcludeArray[@]}"
  local authorsExclusionString_=""

  if [ $nArgs -ge 2 ]; then # parse from command line overriding array
    array_=() # reset array

    for ((i=1; i < $nArgs; i++))
    {
      array_+=( "${args[$i]}" )
    }
  fi

  for author in "${array_[@]}"
  do
    authorsExclusionString_="${authorsExclusionString_} -x \"author:${author}\""
  done
  # return value
  echo "$authorsExclusionString_"
}


if docker_image_exists "$gitinspector_image"
then
    if [ "$1" != "" ]; then
        echo "gitinspector running on $1 : patience..."
    else
        printf "Usage: \e[1m$0 path/to/team/git/repo"
        exit
    fi
    # Build the commands up in parts
    authorsToExclude=$(authors_to_exclude)
    # Contributions sur le plan tests (exclude files that don't match a jest match)
    command="$docker_command -x \"file:^(?!.*(/__tests__/.*|(\\\\.|/)(test|spec))\\.[jt]sx?$).*\" -f ts ${globalOptions} ${authorsToExclude} $1 > \"$reportTests\" && echo \"$reportTests\""
    eval $command
    # Contributions sur le plan modèles
    command="$docker_command -f puml,plantuml ${globalOptions} ${authorsToExclude} > \"$reportModels\" && echo \"$reportModels\""
    eval $command
    # Contributions sur le plan documentation
    command="$docker_command -f md ${globalOptions} ${authorsToExclude} > \"$reportDocumentation\" && echo \"$reportDocumentation\""
    eval $command
    # Contributions sur le plan TypeScript (exclude any jest-matching tests)
    command="$docker_command -x \"file:(/__tests__/.*|(\\.|/)(test|spec))\.[jt]sx?$\" -f ts ${globalOptions} ${authorsToExclude} > \"$reportTypeScript\" && echo \"$reportTypeScript\""
    eval $command
    # Contributions sur le plan Views
    command="$docker_command -f pug ${globalOptions} ${authorsToExclude} > \"$reportViews\" && echo \"$reportViews\""
    eval $command
else
    printf "Erreur - l'image docker de gitinspector n'est pas présente.\n"
    printf 'Voir https://github.com/ejwa/gitinspector/blob/c891985de3f2a819d8cf84c498251f03650df39c/Dockerfile'
fi
```

Si quelqu'un peut le tester sur une autre machine que Windows, je pourrai mettre à jour le gist pour ce script. @yvanross @Olon11

**Comment by Olon11** [comment]
Malheureusement, j'ai seulement un ordinateur qui fonctionne avec Windows.
